# Generated by Django 5.2.8 on 2025-11-22 01:04

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0036_remove_appointment_product_and_more'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electronicsignature',
            options={'ordering': ('-date',), 'verbose_name': 'Electronic Signature', 'verbose_name_plural': 'Electronic Signatures'},
        ),
        migrations.AlterModelOptions(
            name='independentcontractorterms',
            options={'ordering': ('-date',), 'verbose_name': 'Independent Contractor Terms', 'verbose_name_plural': 'Independent Contractor Terms'},
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='staff.independentcontractorterms'),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='initials',
            field=models.CharField(help_text="Staff member's initials", max_length=5),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronic_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='independentcontractorterms',
            name='document',
            field=tinymce.models.HTMLField(help_text='Terms and conditions document'),
        ),
        migrations.AlterUniqueTogether(
            name='electronicsignature',
            unique_together={('document', 'staff_member')},
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('reviewed', 'Reviewed by Student'), ('revised', 'Revised'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('title', models.CharField(default='Tutoring Services Proposal', max_length=255)),
                ('introduction', tinymce.models.HTMLField(blank=True, help_text='Introduction/cover letter text', null=True)),
                ('terms_and_conditions', tinymce.models.HTMLField(blank=True, help_text='Terms and conditions', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not visible to student)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('has_payment_plan', models.BooleanField(default=False)),
                ('payment_plan_months', models.IntegerField(default=1, help_text='Number of months for payment plan')),
                ('payment_plan_start_date', models.DateField(blank=True, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProposalComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=10)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes (not visible to student)')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='staff.proposal')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProposalLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Item description', max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this item', null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.product')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposallineitem_set', to='staff.proposal')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ProposalPaymentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_payments', models.IntegerField(default=1)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Bi-weekly'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('first_payment_date', models.DateField()),
                ('first_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('regular_payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='staff.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField(default=1)),
                ('notes', models.TextField(help_text='What changed in this revision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='staff.proposal')),
                ('revised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-revision_number',),
                'unique_together': {('proposal', 'revision_number')},
            },
        ),
    ]
