# Generated by Django 3.0.5 on 2020-04-22 03:03

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrillTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', tinymce.models.HTMLField()),
                ('a', tinymce.models.HTMLField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drill.DrillTopic')),
            ],
        ),
    ]
