# Generated by Django 2.1.4 on 2018-12-22 08:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.IntegerField(choices=[(0, 'USMLE Step 1'), (1, 'USMLE Step 2CK'), (2, 'USMLE Step 2CS'), (3, 'USMLE Step 3'), (4, 'USMLE Specialty Board Certification'), (5, 'Other')])),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255, verbose_name='First name')),
                ('l_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254)),
                ('graduation_year', models.IntegerField(help_text="Enter all 4 digits. If you haven't graduated yet, enter the year you expect to graduate.", validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)])),
                ('degree', models.IntegerField(choices=[(0, 'M.D.'), (1, 'D.O.')])),
                ('exam', models.IntegerField(choices=[(0, 'USMLE Step 1'), (1, 'USMLE Step 2CK'), (2, 'USMLE Step 2CS'), (3, 'USMLE Step 3'), (4, 'USMLE Specialty Board Certification'), (5, 'Other')], help_text='Choose the exam you are preparing for.')),
                ('test_date', models.DateField(blank=True, help_text='Enter the date that you need to complete the test by or the date you are scheduled to take it.', null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='examscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Student'),
        ),
    ]
