# Generated by Django 2.1.4 on 2018-12-22 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.IntegerField(choices=[(0, 'M.D.'), (1, 'D.O.')], help_text='M.D. or D.O.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_year',
            field=models.IntegerField(help_text="Enter all 4 digits. If you haven't graduated yet, enter the year you expect to graduate.", validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
