# Generated by Django 2.1.4 on 2019-01-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20190102_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='in_person_appt_qty',
            field=models.SmallIntegerField(default=0, verbose_name='Appointments In Person'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='remote_appt_qty',
            field=models.SmallIntegerField(default=0, verbose_name='Appointments Remotely'),
        ),
    ]
