# Generated by Django 2.1.4 on 2018-12-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20181222_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='l_name',
        ),
    ]
