# Generated by Django 2.1.4 on 2019-02-17 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20190211_2238'),
    ]

    operations = [
        migrations.RenameModel('Payment', 'Order'),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.SmallIntegerField()),
                ('charge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Product')),
            ],
        ),
    ]
