# Generated by Django 2.1.4 on 2019-02-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20190217_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exam',
            field=models.IntegerField(blank=True, choices=[(4, 'COMLEX Level 1'), (5, 'COMLEX Level 2'), (6, 'COMLEX Level 3'), (8, 'Medical School Year 1 & 2 Coaching'), (9, 'Medical School Year 3 & 4 Coaching'), (7, 'Specialty Board Certification'), (0, 'USMLE Step 1'), (1, 'USMLE Step 2CK'), (2, 'USMLE Step 2CS'), (3, 'USMLE Step 3'), (10, 'Other'), (11, 'All')], null=True),
        ),
    ]
