# Generated by Django 2.1.4 on 2019-03-20 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profile.managers


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_auto_20190217_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('duration', models.DurationField()),
                ('duration_access', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.TextField()),
                ('image_path', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('profile.student',),
            managers=[
                ('objects', profile.managers.StudentManager()),
            ],
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Course'),
        ),
    ]
