# Generated by Django 2.1.4 on 2019-03-20 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_auto_20190319_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profile.Product'),
            preserve_default=False,
        ),
    ]
