# Generated by Django 2.1.4 on 2019-03-20 07:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_course_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='agendaitem',
            name='datetime_end',
        ),
        migrations.RemoveField(
            model_name='agendaitem',
            name='datetime_start',
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='time_duration',
            field=models.DurationField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='time_start',
            field=models.TimeField(),
            preserve_default=False,
        ),
    ]
