# Generated by Django 2.1.7 on 2019-04-01 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0014_auto_20190331_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsession',
            name='occurrence',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.Occurrence'),
        ),
    ]
