# Generated by Django 2.2 on 2019-05-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0016_auto_20190403_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupSession',
        ),
    ]
