# Generated by Django 2.2 on 2019-05-12 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_event_calendar_not_null'),
        ('profile', '0017_delete_groupsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_id', models.CharField(help_text='Just enter the numbers, not the hyphens.', max_length=10)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.Event')),
            ],
        ),
    ]
