# Generated by Django 2.2 on 2019-05-13 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_event_calendar_not_null'),
        ('profile', '0018_groupsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='occurrence',
        ),
        migrations.AddField(
            model_name='appointment',
            name='event',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='zoom_id',
            field=models.CharField(blank=True, help_text='Just enter the numbers, not the hyphens.', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='GroupSession',
        ),
    ]
