# Generated by Django 2.2.2 on 2019-06-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0021_auto_20190601_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='marketing_subscription',
            field=models.BooleanField(default=True, verbose_name='Agree to receive marketing emails'),
        ),
    ]
