# Generated by Django 2.2.2 on 2019-07-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0022_student_marketing_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='product_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
