# Generated by Django 2.2.3 on 2019-08-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0025_auto_20190715_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='removed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
