# Generated by Django 2.2.3 on 2019-09-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0026_product_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='product_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
