# Generated by Django 2.2.7 on 2019-11-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0027_auto_20190919_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='account_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
