# Generated by Django 3.2.5 on 2021-07-19 03:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0030_auto_20200916_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', tinymce.models.HTMLField()),
                ('citation', models.CharField(max_length=255)),
            ],
        ),
    ]
