# Generated by Django 3.2.5 on 2022-04-06 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0032_auto_20210727_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('quotation_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_start_date', models.DateField(blank=True, null=True)),
                ('product_end_date', models.DateField(blank=True, null=True)),
                ('qty', models.SmallIntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Price (USD)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='ProductUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_start_date', models.DateField(blank=True, null=True)),
                ('product_end_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.product')),
            ],
        ),
    ]
