# Generated by Django 5.2.8 on 2025-11-22 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0035_student_balance_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='product',
        ),
        migrations.RemoveField(
            model_name='examscore',
            name='student',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='quotationlineitem',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='quotationlineitem',
            name='product',
        ),
        migrations.AddField(
            model_name='student',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current outstanding balance on account', max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, help_text='Stripe Payment Method ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID for balance payments', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='subscription_active',
            field=models.BooleanField(default=False, help_text='Whether subscription is currently active'),
        ),
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(help_text='Stripe Payment Intent ID', max_length=255, unique=True)),
                ('stripe_invoice_id', models.CharField(blank=True, help_text='Stripe Invoice ID', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid in USD', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional Stripe metadata')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='AgendaItem',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='ContentItem',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='ExamScore',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.DeleteModel(
            name='QuotationLineItem',
        ),
    ]
