# Generated by Django 4.2.9 on 2024-01-24 04:00
import accounts.managers
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_joined", models.DateField()),
                ("last_login", models.DateTimeField()),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="School Name",
                    ),
                ),
                (
                    "graduation_year",
                    models.IntegerField(
                        help_text="Enter all 4 digits. If you haven't graduated yet, enter the year you expect to graduate.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2050),
                        ],
                    ),
                ),
                (
                    "degree",
                    models.IntegerField(
                        choices=[(0, "MD"), (1, "DO")], help_text="MD or DO", null=True
                    ),
                ),
                (
                    "exam",
                    models.CharField(
                        help_text="Enter the exam(s) you are preparing for.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "test_date",
                    models.DateField(
                        blank=True,
                        help_text="Enter the date that you need to complete the test by or the date you are scheduled to take it.",
                        null=True,
                    ),
                ),
                ("phone_number", models.CharField(max_length=31, null=True)),
                (
                    "marketing_subscription",
                    models.BooleanField(
                        default=True, verbose_name="Agree to receive marketing emails"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ("last_name",),
            },
            managers=[
                ("objects", accounts.managers.StudentManager()),
            ],
        ),
    ]
