# Generated by Django 4.2.11 on 2024-03-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="degree",
            field=models.IntegerField(choices=[(0, "MD"), (1, "DO")], null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="institution",
            field=models.CharField(
                max_length=255, null=True, verbose_name="School Name"
            ),
        ),
    ]
