# Generated by Django 5.0.3 on 2024-03-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_student_degree_alter_student_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="balance_paid",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
