# Generated by Django 5.0.3 on 2024-03-20 11:37

from django.db import migrations, models
from django.db.models import Value
from django.db.models.functions import Concat


def set_name(apps, schema_editor):
    Student = apps.get_model("accounts", "Student")
    db_alias = schema_editor.connection.alias
    Student.objects.using(db_alias).all().update(
        name=Concat("last_name", Value(", "), "first_name")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_student_balance_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(blank=True, max_length=182),
        ),
        migrations.RunPython(set_name),
    ]
