# Generated by Django 5.2.8 on 2025-11-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_migrate_from_profile'),
    ]

    operations = [
    ]

