# Generated by Django 5.2.8 on 2025-11-25 17:38

import accounts.managers
from django.db import migrations, models


def add_fields_if_not_exists(apps, schema_editor):
    """Add fields only if they don't already exist (for migrated tables)."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check which fields exist
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_schema = 'public' 
            AND table_name = 'accounts_student';
        """)
        existing_columns = {row[0] for row in cursor.fetchall()}
        
        # Fields that might already exist (from profile migration)
        fields_to_add = [
            ('account_balance', 'ALTER TABLE accounts_student ADD COLUMN account_balance NUMERIC(10, 2) DEFAULT 0.0'),
            ('stripe_customer_id', 'ALTER TABLE accounts_student ADD COLUMN stripe_customer_id VARCHAR(255)'),
            ('stripe_payment_method_id', 'ALTER TABLE accounts_student ADD COLUMN stripe_payment_method_id VARCHAR(255)'),
            ('stripe_subscription_id', 'ALTER TABLE accounts_student ADD COLUMN stripe_subscription_id VARCHAR(255)'),
            ('subscription_active', 'ALTER TABLE accounts_student ADD COLUMN subscription_active BOOLEAN DEFAULT FALSE'),
        ]
        
        for field_name, sql in fields_to_add:
            if field_name not in existing_columns:
                try:
                    cursor.execute(sql)
                except Exception:
                    pass  # Field might have been added concurrently


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_create_missing_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('last_name',), 'verbose_name': 'Student'},
        ),
        migrations.AlterModelManagers(
            name='staff',
            managers=[
                ('objects', accounts.managers.StudentManager()),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='student',
                    name='account_balance',
                    field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current outstanding balance on account', max_digits=10),
                ),
                migrations.AddField(
                    model_name='student',
                    name='stripe_customer_id',
                    field=models.CharField(blank=True, help_text='Stripe Customer ID', max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='student',
                    name='stripe_payment_method_id',
                    field=models.CharField(blank=True, help_text='Stripe Payment Method ID', max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='student',
                    name='stripe_subscription_id',
                    field=models.CharField(blank=True, help_text='Stripe Subscription ID for balance payments', max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='student',
                    name='subscription_active',
                    field=models.BooleanField(default=False, help_text='Whether subscription is currently active'),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_fields_if_not_exists, migrations.RunPython.noop),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.IntegerField(choices=[(0, 'MD'), (1, 'DO')], help_text='MD or DO', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='exam',
            field=models.IntegerField(choices=[(4, 'COMLEX Level 1'), (5, 'COMLEX Level 2'), (6, 'COMLEX Level 3'), (8, 'Medical School Year 1 & 2 Coaching'), (9, 'Medical School Year 3 & 4 Coaching'), (7, 'Specialty Board Certification'), (0, 'USMLE Step 1'), (1, 'USMLE Step 2CK'), (3, 'USMLE Step 3'), (10, 'Other'), (11, 'All')], help_text='Choose the exam you are preparing for.', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
