# Generated by Django 2.1.4 on 2019-02-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20190217_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_number',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='order',
            name='in_person_appt_qty',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Appointments In Person'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remote_appt_qty',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Appointments Remotely'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
