# Generated by Django 2.1.7 on 2019-04-01 04:08
# Modified: Removed schedule dependency - schedule app and GroupSession model no longer exist

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_auto_20190331_2205'),
    ]

    operations = [
        # GroupSession model operations removed - model no longer exists
        # Original migration modified GroupSession with reference to schedule.Occurrence
    ]
