# Generated by Django 2.2 on 2019-04-04 02:49
# Modified: Removed schedule dependency - schedule app and Appointment model no longer exist

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0015_auto_20190401_0010'),
    ]

    operations = [
        # Appointment model operations removed - model no longer exists
        # Original migration modified Appointment with reference to schedule.Occurrence
        migrations.AddField(
            model_name='examscore',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='examscore',
            name='score',
            field=models.IntegerField(choices=[(1, 'Pass'), (0, 'Fail')]),
        ),
    ]
