# Generated by Django 2.2 on 2019-05-12 22:24
# Modified: Removed schedule dependency - schedule app no longer exists

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0017_delete_groupsession'),
    ]

    operations = [
        # GroupSession model creation removed - model no longer exists
        # Original migration created GroupSession with reference to schedule.Event
    ]
