# Generated by Django 2.2 on 2019-05-13 02:47
# Modified: Removed schedule dependency - schedule app and Appointment/GroupSession models no longer exist

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0018_groupsession'),
    ]

    operations = [
        # All operations removed - Appointment and GroupSession models no longer exist
        # Original migration modified Appointment model with reference to schedule.Event
    ]
