# Generated by Django 2.2 on 2019-06-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0020_auto_20190513_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='qty',
            field=models.SmallIntegerField(verbose_name='Quantity'),
        ),
    ]
