# Generated by Django 2.2.2 on 2019-07-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0023_orderlineitem_product_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='products',
            field=models.ManyToManyField(blank=True, to='profile.Product'),
        ),
    ]
