# Generated by Django 2.2.3 on 2019-07-16 03:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0024_student_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='student',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
