# Generated by Django 3.0.5 on 2020-09-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0028_product_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
