# Generated by Django 3.0.5 on 2020-09-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0029_student_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='School Name'),
        ),
    ]
