# Generated by Django 3.2.5 on 2021-07-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0031_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterField(
            model_name='examscore',
            name='exam',
            field=models.IntegerField(choices=[(4, 'COMLEX Level 1'), (5, 'COMLEX Level 2'), (6, 'COMLEX Level 3'), (8, 'Medical School Year 1 & 2 Coaching'), (9, 'Medical School Year 3 & 4 Coaching'), (7, 'Specialty Board Certification'), (0, 'USMLE Step 1'), (1, 'USMLE Step 2CK'), (3, 'USMLE Step 3'), (10, 'Other'), (11, 'All')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='exam',
            field=models.IntegerField(choices=[(4, 'COMLEX Level 1'), (5, 'COMLEX Level 2'), (6, 'COMLEX Level 3'), (8, 'Medical School Year 1 & 2 Coaching'), (9, 'Medical School Year 3 & 4 Coaching'), (7, 'Specialty Board Certification'), (0, 'USMLE Step 1'), (1, 'USMLE Step 2CK'), (3, 'USMLE Step 3'), (10, 'Other'), (11, 'All')], help_text='Choose the exam you are preparing for.', null=True),
        ),
    ]
