# Generated by Django 3.2.5 on 2022-04-06 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0033_productusers_quotation_quotationlineitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductUsers',
            new_name='ProductUser',
        ),
    ]
